# This is a basic workflow to help you get started with Actions

name: NestedRunner

# Controls when the workflow will run
on: workflow_dispatch

  # Triggers the workflow on push or pull request events but only for the "main" branch
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Run a one-line script 1
      run: echo Hello, world!      
      
   job_number1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 1
        run: echo Hello, world!
   job_number2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 2
        run: echo Hello, world!!
   job_number3:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 3
        run: echo Hello, world!!
   job_number4:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 4
        run: echo Hello, world!!
   job_number5:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 5
        run: echo Hello, world!!
   job_number6:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 6
        run: echo Hello, world!!
   job_number7:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script 7
        run: echo Hello, world!!

   build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
